version: '3'
services:
    nginx:
      restart: always
      build:
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports:
        - '3050:80'
    hsse-server:
      restart: "no"
      build: 
        context: ./server
        dockerfile: Dockerfile.dev
      volumes:
        - ./server:/app:rw
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true
        - BACKEND_SERVER=hsse_server
        - HSSE_SES_ACCESS_KEY=
        - HSSE_SES_SECRET_KEY=
        - MONGO_URI=mongodb://sakksoftware:sakk11software@ds121282.mlab.com:21282/machealthsci-dev
        - NODE_ENV=development
        - JWT_SECRET=akfjlaksdjlasfjasdfljiasdfasfksldf
        - FRONTEND_SERVER=http://localhost:3050
        - BACKEND_SERVER=http://localhost:3050/api
        - REGION=us-east-1
    hsse-admin-client:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
        - ./client:/app:rw
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true
        - BACKEND_SERVER=http://localhost:3050/api
    hsse-admin-client-test:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
        - ./client:/app:rw
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true
        - BACKEND_SERVER=http://localhost:3050/api
      command: ["npm", "run", "test"]